{% set name = "jaxsim" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxsim-{{ version }}.tar.gz{{ version }}.tar.gz
  sha256: 27d0dec121b86c5c4d93d918ca7d782c5fa775e7098d1eb81325f85ba149c093

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - wheel
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.11
    - coloredlogs
    - jax >=0.4.13
    - jaxlib
    - jaxlie >=1.3.0
    - jax-dataclasses >=1.4.0
    - pptree
    - rod

test:
  imports:
    - jaxsim
  commands:
    - pip check
    - test "$(pip list | grep jaxsim | awk '{print $2}')" == "$PKG_VERSION"
  requires:
    - pip

about:
  home: https://github.com/ami-iit/jaxsim
  summary: A physics engine in reduced coordinates implemented with JAX.
  dev_url: https://github.com/ami-iit/jaxsim
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flferretti
    - diegoferigo
    - traversaro
